image: Visual Studio 2015

environment:
  matrix:
  - QT: C:\Qt\5.7\msvc2015_64
    PLATFORM: amd64
    COMPILER: msvc
    VSVER: 14

clone_depth: 1

init:
  - set TAG_NAME=%APPVEYOR_REPO_TAG_NAME%

build_script:
  - call "appveyor/build_windows.cmd"

artifacts:
  - path: build\windows\msvc\x86_64\release\QtQuickVR_$(appveyor_repo_tag_name)_windows_x86_64_portable.zip
    name: portable
  - path: installer\windows\x86_64\QtQuickVR_$(appveyor_repo_tag_name)_windows_x86_64_installer.exe
    name: installer
